- name: Setup Redis Yum Repos
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update redis configuration - listner address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
