- name: Configure YUM repos
  ansible.builtin.shell: curl -fssL https://rpm.nodesource.com/setup.lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App user, Download and Extract {{COMPONENT}} Content
  ansible.builtin.include_role:
    name: common
  tasks_from: download

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Setup Systemd
  ansible.builtin.include_role:
    name: common
  tasks_from: systemd
