## If any task is changed and if we want to run another task then handlers comes into picture.
##By default handlers run at the ending of the play, This behaviour can be changed as well and run immediate also.

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted